<?php
/**
 * @category   Udeytech
 * @package    Udeytech_Dubey
 * @author     mridubey57@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Udeytech\Dubey\Block;

use Magento\Framework\View\Element\Template\Context;
use Udeytech\Dubey\Model\DubeyFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Dubey View block
 */
class DubeyView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Dubey
     */
    protected $_dubey;
    public function __construct(
        Context $context,
        DubeyFactory $dubey,
        FilterProvider $filterProvider
    ) {
        $this->_dubey = $dubey;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Udeytech Dubey Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $dubey = $this->_dubey->create();
        $singleData = $dubey->load($id);
        if($singleData->getDubeyId() || $singleData['dubey_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}